services:

  web_frontend:
    build:
      context: frontend
      target: development
    restart: always
    container_name: web_frontend
    ports:
      - 8127:8000
    env_file:
      - .env
    command: pnpm run dev
    depends_on:
      - backend


  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./backend/database:/app/database
    

  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8080

volumes:
    postgres_data:
