"""Initial

Revision ID: 1a85f439292b
Revises: 
Create Date: 2024-10-18 14:53:30.592512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a85f439292b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Currency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.String(length=100), nullable=True),
    sa.Column('sender', sa.String(length=100), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['Currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transactions')
    op.drop_table('Currency')
    # ### end Alembic commands ###
